---
test:
  name: 6G-Fabric-Benchmark
  description: Benchmark for 6G Fabric Network with Random Locations
  clients:
    type: local
    number: 2
  rounds:
    - label: GeoAssign
      txNumber: 1000
      rateControl:
        type: fixed-rate
        opts:
          tps: 100
      workload:
        module: workload/geoassign.js
    - label: GeoUpdate
      txNumber: 1000
      rateControl:
        type: fixed-rate
        opts:
          tps: 100
      workload:
        module: workload/geoupdate.js
    - label: GeoHandover
      txNumber: 1000
      rateControl:
        type: fixed-rate
        opts:
          tps: 100
      workload:
        module: workload/geohandover.js
    - label: AuthUser
      txNumber: 1000
      rateControl:
        type: fixed-rate
        opts:
          tps: 100
      workload:
        module: workload/authuser.js
    - label: AuthIoT
      txNumber: 1000
      rateControl:
        type: fixed-rate
        opts:
          tps: 100
      workload:
        module: workload/authiot.js
    - label: ConnectUser
      txNumber: 1000
      rateControl:
        type: fixed-rate
        opts:
          tps: 100
      workload:
        module: workload/connectuser.js
    - label: ConnectIoT
      txNumber: 1000
      rateControl:
        type: fixed-rate
        opts:
          tps: 100
      workload:
        module: workload/connectiot.js
    - label: BandwidthAlloc
      txNumber: 1000
      rateControl:
        type: fixed-rate
        opts:
          tps: 100
      workload:
        module: workload/bandwidthalloc.js
    - label: AuthAntenna
      txNumber: 1000
      rateControl:
        type: fixed-rate
        opts:
          tps: 100
      workload:
        module: workload/authantenna.js
    - label: RegisterUser
      txNumber: 1000
      rateControl:
        type: fixed-rate
        opts:
          tps: 100
      workload:
        module: workload/registeruser.js
    - label: RegisterIoT
      txNumber: 1000
      rateControl:
        type: fixed-rate
        opts:
          tps: 100
      workload:
        module: workload/registeriot.js
    - label: RevokeUser
      txNumber: 1000
      rateControl:
        type: fixed-rate
        opts:
          tps: 100
      workload:
        module: workload/revokeuser.js
    - label: RevokeIoT
      txNumber: 1000
      rateControl:
        type: fixed-rate
        opts:
          tps: 100
      workload:
        module: workload/revokeiot.js
    - label: RoleAssign
      txNumber: 1000
      rateControl:
        type: fixed-rate
        opts:
          tps: 100
      workload:
        module: workload/roleassign.js
    - label: AccessControl
      txNumber: 1000
      rateControl:
        type: fixed-rate
        opts:
          tps: 100
      workload:
        module: workload/accesscontrol.js
    - label: AuditIdentity
      txNumber: 1000
      rateControl:
        type: fixed-rate
        opts:
          tps: 100
      workload:
        module: workload/auditidentity.js
    - label: IoTBandwidth
      txNumber: 1000
      rateControl:
        type: fixed-rate
        opts:
          tps: 100
      workload:
        module: workload/iotbandwidth.js
    - label: AntennaLoad
      txNumber: 1000
      rateControl:
        type: fixed-rate
        opts:
          tps: 100
      workload:
        module: workload/antennaload.js
    - label: ResourceRequest
      txNumber: 1000
      rateControl:
        type: fixed-rate
        opts:
          tps: 100
      workload:
        module: workload/resourcerequest.js
    - label: QoSManage
      txNumber: 1000
      rateControl:
        type: fixed-rate
        opts:
          tps: 100
      workload:
        module: workload/qosmanage.js
    - label: SpectrumShare
      txNumber: 1000
      rateControl:
        type: fixed-rate
        opts:
          tps: 100
      workload:
        module: workload/spectrumshare.js
    - label: PriorityAssign
      txNumber: 1000
      rateControl:
        type: fixed-rate
        opts:
          tps: 100
      workload:
        module: workload/priorityassign.js
    - label: ResourceAudit
      txNumber: 1000
      rateControl:
        type: fixed-rate
        opts:
          tps: 100
      workload:
        module: workload/resourceaudit.js
    - label: LoadBalance
      txNumber: 1000
      rateControl:
        type: fixed-rate
        opts:
          tps: 100
      workload:
        module: workload/loadbalance.js
    - label: DynamicAlloc
      txNumber: 1000
      rateControl:
        type: fixed-rate
        opts:
          tps: 100
      workload:
        module: workload/dynamicaloc.js
    - label: AntennaStatus
      txNumber: 1000
      rateControl:
        type: fixed-rate
        opts:
          tps: 100
      workload:
        module: workload/antennastatus.js
    - label: IoTStatus
      txNumber: 1000
      rateControl:
        type: fixed-rate
        opts:
          tps: 100
      workload:
        module: workload/iotstatus.js
    - label: NetworkPerf
      txNumber: 1000
      rateControl:
        type: fixed-rate
        opts:
          tps: 100
      workload:
        module: workload/networkperf.js
    - label: UserActivity
      txNumber: 1000
      rateControl:
        type: fixed-rate
        opts:
          tps: 100
      workload:
        module: workload/useractivity.js
    - label: FaultDetect
      txNumber: 1000
      rateControl:
        type: fixed-rate
        opts:
          tps: 100
      workload:
        module: workload/faultdetect.js
    - label: IoTFault
      txNumber: 1000
      rateControl:
        type: fixed-rate
        opts:
          tps: 100
      workload:
        module: workload/iotfault.js
    - label: TrafficMonitor
      txNumber: 1000
      rateControl:
        type: fixed-rate
        opts:
          tps: 100
      workload:
        module: workload/trafficmonitor.js
    - label: ReportGenerate
      txNumber: 1000
      rateControl:
        type: fixed-rate
        opts:
          tps: 100
      workload:
        module: workload/reportgenerate.js
    - label: LatencyTrack
      txNumber: 1000
      rateControl:
        type: fixed-rate
        opts:
          tps: 100
      workload:
        module: workload/latencytrack.js
    - label: EnergyMonitor
      txNumber: 1000
      rateControl:
        type: fixed-rate
        opts:
          tps: 100
      workload:
        module: workload/energymonitor.js
    - label: Roaming
      txNumber: 1000
      rateControl:
        type: fixed-rate
        opts:
          tps: 100
      workload:
        module: workload/roaming.js
    - label: SessionTrack
      txNumber: 1000
      rateControl:
        type: fixed-rate
        opts:
          tps: 100
      workload:
        module: workload/sessiontrack.js
    - label: IoTSession
      txNumber: 1000
      rateControl:
        type: fixed-rate
        opts:
          tps: 100
      workload:
        module: workload/iotsession.js
    - label: Disconnect
      txNumber: 1000
      rateControl:
        type: fixed-rate
        opts:
          tps: 100
      workload:
        module: workload/disconnect.js
    - label: Billing
      txNumber: 1000
      rateControl:
        type: fixed-rate
        opts:
          tps: 100
      workload:
        module: workload/billing.js
    - label: TransactionLog
      txNumber: 1000
      rateControl:
        type: fixed-rate
        opts:
          tps: 100
      workload:
        module: workload/transactionlog.js
    - label: ConnectionAudit
      txNumber: 1000
      rateControl:
        type: fixed-rate
        opts:
          tps: 100
      workload:
        module: workload/connectionaudit.js
    - label: DataEncrypt
      txNumber: 1000
      rateControl:
        type: fixed-rate
        opts:
          tps: 100
      workload:
        module: workload/dataencrypt.js
    - label: IoTEncrypt
      txNumber: 1000
      rateControl:
        type: fixed-rate
        opts:
          tps: 100
      workload:
        module: workload/iotencrypt.js
    - label: AccessLog
      txNumber: 1000
      rateControl:
        type: fixed-rate
        opts:
          tps: 100
      workload:
        module: workload/accesslog.js
    - label: IntrusionDetect
      txNumber: 1000
      rateControl:
        type: fixed-rate
        opts:
          tps: 100
      workload:
        module: workload/intrusiondetect.js
    - label: KeyManage
      txNumber: 1000
      rateControl:
        type: fixed-rate
        opts:
          tps: 100
      workload:
        module: workload/keymanage.js
    - label: PrivacyPolicy
      txNumber: 1000
      rateControl:
        type: fixed-rate
        opts:
          tps: 100
      workload:
        module: workload/privacypolicy.js
    - label: SecureChannel
      txNumber: 1000
      rateControl:
        type: fixed-rate
        opts:
          tps: 100
      workload:
        module: workload/securechannel.js
    - label: AuditSecurity
      txNumber: 1000
      rateControl:
        type: fixed-rate
        opts:
          tps: 100
      workload:
        module: workload/auditsecurity.js
    - label: EnergyOptimize
      txNumber: 1000
      rateControl:
        type: fixed-rate
        opts:
          tps: 100
      workload:
        module: workload/energyoptimize.js
    - label: NetworkOptimize
      txNumber: 1000
      rateControl:
        type: fixed-rate
        opts:
          tps: 100
      workload:
        module: workload/networkoptimize.js
    - label: IoTAnalytics
      txNumber: 1000
      rateControl:
        type: fixed-rate
        opts:
          tps: 100
      workload:
        module: workload/iotanalytics.js
    - label: UserAnalytics
      txNumber: 1000
      rateControl:
        type: fixed-rate
        opts:
          tps: 100
      workload:
        module: workload/useranalytics.js
    - label: SecurityMonitor
      txNumber: 1000
      rateControl:
        type: fixed-rate
        opts:
          tps: 100
      workload:
        module: workload/securitymonitor.js
    - label: QuantumEncrypt
      txNumber: 1000
      rateControl:
        type: fixed-rate
        opts:
          tps: 100
      workload:
        module: workload/quantumencrypt.js
    - label: MultiAntenna
      txNumber: 1000
      rateControl:
        type: fixed-rate
        opts:
          tps: 100
      workload:
        module: workload/multiantenna.js
    - label: EdgeCompute
      txNumber: 1000
      rateControl:
        type: fixed-rate
        opts:
          tps: 100
      workload:
        module: workload/edgecompute.js
    - label: IoTHealth
      txNumber: 1000
      rateControl:
        type: fixed-rate
        opts:
          tps: 100
      workload:
        module: workload/iothealth.js
    - label: NetworkHealth
      txNumber: 1000
      rateControl:
        type: fixed-rate
        opts:
          tps: 100
      workload:
        module: workload/networkhealth.js
    - label: DataIntegrity
      txNumber: 1000
      rateControl:
        type: fixed-rate
        opts:
          tps: 100
      workload:
        module: workload/dataintegrity.js
    - label: PolicyEnforce
      txNumber: 1000
      rateControl:
        type: fixed-rate
        opts:
          tps: 100
      workload:
        module: workload/policyenforce.js
    - label: DynamicRouting
      txNumber: 1000
      rateControl:
        type: fixed-rate
        opts:
          tps: 100
      workload:
        module: workload/dynamicrouting.js
    - label: BandwidthShare
      txNumber: 1000
      rateControl:
        type: fixed-rate
        opts:
          tps: 100
      workload:
        module: workload/bandwidthshare.js
    - label: LatencyOptimize
      txNumber: 1000
      rateControl:
        type: fixed-rate
        opts:
          tps: 100
      workload:
        module: workload/latencyoptimize.js
    - label: FaultPredict
      txNumber: 1000
      rateControl:
        type: fixed-rate
        opts:
          tps: 100
      workload:
        module: workload/faultpredict.js
    - label: IoTConfig
      txNumber: 1000
      rateControl:
        type: fixed-rate
        opts:
          tps: 100
      workload:
        module: workload/iotconfig.js
    - label: UserConfig
      txNumber: 1000
      rateControl:
        type: fixed-rate
        opts:
          tps: 100
      workload:
        module: workload/userconfig.js
    - label: AntennaConfig
      txNumber: 1000
      rateControl:
        type: fixed-rate
        opts:
          tps: 100
      workload:
        module: workload/antennaconfig.js
    - label: PerformanceAudit
      txNumber: 1000
      rateControl:
        type: fixed-rate
        opts:
          tps: 100
      workload:
        module: workload/performanceaudit.js
    - label: SecurityAudit
      txNumber: 1000
      rateControl:
        type: fixed-rate
        opts:
          tps: 100
      workload:
        module: workload/securityaudit.js
    - label: DataAnalytics
      txNumber: 1000
      rateControl:
        type: fixed-rate
        opts:
          tps: 100
      workload:
        module: workload/dataanalytics.js
    - label: RealTimeMonitor
      txNumber: 1000
      rateControl:
        type: fixed-rate
        opts:
          tps: 100
      workload:
        module: workload/realtimemonitor.js
monitor:
  type: docker
  docker:
    name: []
  interval: 2
