test:
  name: 6G Fabric Benchmark
  description: Benchmark for 6G Fabric Network with selected chaincodes across selected channels
  workers:
    number: 10
  rounds:
    - label: ResourceAllocate-generalchannelapp
      description: Test ResourceAllocate chaincode on generalchannelapp
      txNumber: 1000
      rateControl:
        type: fixed-rate
        opts:
          tps: 100
      workload:
        module: ./workload/callback.js
        arguments:
          chaincodeID: ResourceAllocate
          channel: generalchannelapp
          txNumber: 1000
          args:
            - function: AssignResource
              args: ["resource1", "100", "200", "1000"]
            - function: QueryResource
              args: ["resource1"]
    - label: ResourceAllocate-iotchannelapp
      description: Test ResourceAllocate chaincode on iotchannelapp
      txNumber: 1000
      rateControl:
        type: fixed-rate
        opts:
          tps: 100
      workload:
        module: ./workload/callback.js
        arguments:
          chaincodeID: ResourceAllocate
          channel: iotchannelapp
          txNumber: 1000
          args:
            - function: AssignResource
              args: ["resource1", "100", "200", "1000"]
            - function: QueryResource
              args: ["resource1"]
    # ... (978 rounds omitted; full file generated by generateBenchmarkConfig.sh)
