name: Fabric Network
version: 2.0.0
caliper:
  blockchain: fabric
  command:
    start: docker-compose -f docker-compose.yaml up -d
    end: docker-compose -f docker-compose.yaml down
fabric:
  network:
    orderers:
      - orderer.example.com:
          url: grpc://localhost:7050
          grpcOptions:
            ssl-target-name-override: orderer.example.com
          tlsCACerts:
            path: crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/tls/ca.crt
    peers:
      - peer0.org1.example.com:
          url: grpc://localhost:7051
          grpcOptions:
            ssl-target-name-override: peer0.org1.example.com
          tlsCACerts:
            path: crypto-config/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/ca.crt
      - peer0.org2.example.com:
          url: grpc://localhost:8051
          grpcOptions:
            ssl-target-name-override: peer0.org2.example.com
          tlsCACerts:
            path: crypto-config/peerOrganizations/org2.example.com/peers/peer0.org2.example.com/tls/ca.crt
      - peer0.org3.example.com:
          url: grpc://localhost:9051
          grpcOptions:
            ssl-target-name-override: peer0.org3.example.com
          tlsCACerts:
            path: crypto-config/peerOrganizations/org3.example.com/peers/peer0.org3.example.com/tls/ca.crt
      - peer0.org4.example.com:
          url: grpc://localhost:10051
          grpcOptions:
            ssl-target-name-override: peer0.org4.example.com
          tlsCACerts:
            path: crypto-config/peerOrganizations/org4.example.com/peers/peer0.org4.example.com/tls/ca.crt
      - peer0.org5.example.com:
          url: grpc://localhost:11051
          grpcOptions:
            ssl-target-name-override: peer0.org5.example.com
          tlsCACerts:
            path: crypto-config/peerOrganizations/org5.example.com/peers/peer0.org5.example.com/tls/ca.crt
      - peer0.org6.example.com:
          url: grpc://localhost:12051
          grpcOptions:
            ssl-target-name-override: peer0.org6.example.com
          tlsCACerts:
            path: crypto-config/peerOrganizations/org6.example.com/peers/peer0.org6.example.com/tls/ca.crt
      - peer0.org7.example.com:
          url: grpc://localhost:13051
          grpcOptions:
            ssl-target-name-override: peer0.org7.example.com
          tlsCACerts:
            path: crypto-config/peerOrganizations/org7.example.com/peers/peer0.org7.example.com/tls/ca.crt
      - peer0.org8.example.com:
          url: grpc://localhost:14051
          grpcOptions:
            ssl-target-name-override: peer0.org8.example.com
          tlsCACerts:
            path: crypto-config/peerOrganizations/org8.example.com/peers/peer0.org8.example.com/tls/ca.crt
      - peer0.org9.example.com:
          url: grpc://localhost:15051
          grpcOptions:
            ssl-target-name-override: peer0.org9.example.com
          tlsCACerts:
            path: crypto-config/peerOrganizations/org9.example.com/peers/peer0.org9.example.com/tls/ca.crt
      - peer0.org10.example.com:
          url: grpc://localhost:16051
          grpcOptions:
            ssl-target-name-override: peer0.org10.example.com
          tlsCACerts:
            path: crypto-config/peerOrganizations/org10.example.com/peers/peer0.org10.example.com/tls/ca.crt
    channels:
      generalchannelapp:
        created: true
        orderers: [orderer.example.com]
        peers:
          peer0.org1.example.com: { endorsingPeer: true, chaincodeQuery: true, ledgerQuery: true, eventSource: true }
          peer0.org2.example.com: { endorsingPeer: true, chaincodeQuery: true, ledgerQuery: true, eventSource: true }
          peer0.org3.example.com: { endorsingPeer: true, chaincodeQuery: true, ledgerQuery: true, eventSource: true }
          peer0.org4.example.com: { endorsingPeer: true, chaincodeQuery: true, ledgerQuery: true, eventSource: true }
          peer0.org5.example.com: { endorsingPeer: true, chaincodeQuery: true, ledgerQuery: true, eventSource: true }
          peer0.org6.example.com: { endorsingPeer: true, chaincodeQuery: true, ledgerQuery: true, eventSource: true }
          peer0.org7.example.com: { endorsingPeer: true, chaincodeQuery: true, ledgerQuery: true, eventSource: true }
          peer0.org8.example.com: { endorsingPeer: true, chaincodeQuery: true, ledgerQuery: true, eventSource: true }
          peer0.org9.example.com: { endorsingPeer: true, chaincodeQuery: true, ledgerQuery: true, eventSource: true }
          peer0.org10.example.com: { endorsingPeer: true, chaincodeQuery: true, ledgerQuery: true, eventSource: true }
      iotchannelapp:
        created: true
        orderers: [orderer.example.com]
        peers:
          peer0.org1.example.com: { endorsingPeer: true, chaincodeQuery: true, ledgerQuery: true, eventSource: true }
          peer0.org2.example.com: { endorsingPeer: true, chaincodeQuery: true, ledgerQuery: true, eventSource: true }
          peer0.org3.example.com: { endorsingPeer: true, chaincodeQuery: true, ledgerQuery: true, eventSource: true }
          peer0.org4.example.com: { endorsingPeer: true, chaincodeQuery: true, ledgerQuery: true, eventSource: true }
          peer0.org5.example.com: { endorsingPeer: true, chaincodeQuery: true, ledgerQuery: true, eventSource: true }
          peer0.org6.example.com: { endorsingPeer: true, chaincodeQuery: true, ledgerQuery: true, eventSource: true }
          peer0.org7.example.com: { endorsingPeer: true, chaincodeQuery: true, ledgerQuery: true, eventSource: true }
          peer0.org8.example.com: { endorsingPeer: true, chaincodeQuery: true, ledgerQuery: true, eventSource: true }
          peer0.org9.example.com: { endorsingPeer: true, chaincodeQuery: true, ledgerQuery: true, eventSource: true }
          peer0.org10.example.com: { endorsingPeer: true, chaincodeQuery: true, ledgerQuery: true, eventSource: true }
      securitychannelapp:
        created: true
        orderers: [orderer.example.com]
        peers:
          peer0.org1.example.com: { endorsingPeer: true, chaincodeQuery: true, ledgerQuery: true, eventSource: true }
          peer0.org2.example.com: { endorsingPeer: true, chaincodeQuery: true, ledgerQuery: true, eventSource: true }
          peer0.org3.example.com: { endorsingPeer: true, chaincodeQuery: true, ledgerQuery: true, eventSource: true }
          peer0.org4.example.com: { endorsingPeer: true, chaincodeQuery: true, ledgerQuery: true, eventSource: true }
          peer0.org5.example.com: { endorsingPeer: true, chaincodeQuery: true, ledgerQuery: true, eventSource: true }
          peer0.org6.example.com: { endorsingPeer: true, chaincodeQuery: true, ledgerQuery: true, eventSource: true }
          peer0.org7.example.com: { endorsingPeer: true, chaincodeQuery: true, ledgerQuery: true, eventSource: true }
          peer0.org8.example.com: { endorsingPeer: true, chaincodeQuery: true, ledgerQuery: true, eventSource: true }
          peer0.org9.example.com: { endorsingPeer: true, chaincodeQuery: true, ledgerQuery: true, eventSource: true }
          peer0.org10.example.com: { endorsingPeer: true, chaincodeQuery: true, ledgerQuery: true, eventSource: true }
      monitoringchannelapp:
        created: true
        orderers: [orderer.example.com]
        peers:
          peer0.org1.example.com: { endorsingPeer: true, chaincodeQuery: true, ledgerQuery: true, eventSource: true }
          peer0.org2.example.com: { endorsingPeer: true, chaincodeQuery: true, ledgerQuery: true, eventSource: true }
          peer0.org3.example.com: { endorsingPeer: true, chaincodeQuery: true, ledgerQuery: true, eventSource: true }
          peer0.org4.example.com: { endorsingPeer: true, chaincodeQuery: true, ledgerQuery: true, eventSource: true }
          peer0.org5.example.com: { endorsingPeer: true, chaincodeQuery: true, ledgerQuery: true, eventSource: true }
          peer0.org6.example.com: { endorsingPeer: true, chaincodeQuery: true, ledgerQuery: true, eventSource: true }
          peer0.org7.example.com: { endorsingPeer: true, chaincodeQuery: true, ledgerQuery: true, eventSource: true }
          peer0.org8.example.com: { endorsingPeer: true, chaincodeQuery: true, ledgerQuery: true, eventSource: true }
          peer0.org9.example.com: { endorsingPeer: true, chaincodeQuery: true, ledgerQuery: true, eventSource: true }
          peer0.org10.example.com: { endorsingPeer: true, chaincodeQuery: true, ledgerQuery: true, eventSource: true }
      org1channelapp:
        created: true
        orderers: [orderer.example.com]
        peers:
          peer0.org1.example.com: { endorsingPeer: true, chaincodeQuery: true, ledgerQuery: true, eventSource: true }
      org2channelapp:
        created: true
        orderers: [orderer.example.com]
        peers:
          peer0.org2.example.com: { endorsingPeer: true, chaincodeQuery: true, ledgerQuery: true, eventSource: true }
      org3channelapp:
        created: true
        orderers: [orderer.example.com]
        peers:
          peer0.org3.example.com: { endorsingPeer: true, chaincodeQuery: true, ledgerQuery: true, eventSource: true }
      org4channelapp:
        created: true
        orderers: [orderer.example.com]
        peers:
          peer0.org4.example.com: { endorsingPeer: true, chaincodeQuery: true, ledgerQuery: true, eventSource: true }
      org5channelapp:
        created: true
        orderers: [orderer.example.com]
        peers:
          peer0.org5.example.com: { endorsingPeer: true, chaincodeQuery: true, ledgerQuery: true, eventSource: true }
      org6channelapp:
        created: true
        orderers: [orderer.example.com]
        peers:
          peer0.org6.example.com: { endorsingPeer: true, chaincodeQuery: true, ledgerQuery: true, eventSource: true }
      org7channelapp:
        created: true
        orderers: [orderer.example.com]
        peers:
          peer0.org7.example.com: { endorsingPeer: true, chaincodeQuery: true, ledgerQuery: true, eventSource: true }
      org8channelapp:
        created: true
        orderers: [orderer.example.com]
        peers:
          peer0.org8.example.com: { endorsingPeer: true, chaincodeQuery: true, ledgerQuery: true, eventSource: true }
      org9channelapp:
        created: true
        orderers: [orderer.example.com]
        peers:
          peer0.org9.example.com: { endorsingPeer: true, chaincodeQuery: true, ledgerQuery: true, eventSource: true }
      org10channelapp:
        created: true
        orderers: [orderer.example.com]
        peers:
          peer0.org10.example.com: { endorsingPeer: true, chaincodeQuery: true, ledgerQuery: true, eventSource: true }
