version: '2'
networks:
  fabric:
    name: fabric
services:
  orderer.example.com:
    container_name: orderer.example.com
    image: hyperledger/fabric-orderer:2.4
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/genesis.block
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_LISTENPORT=7050
      - ORDERER_GENERAL_BOOTSTRAPMETHOD=file
      - ORDERER_GENERAL_BOOTSTRAPFILE=/var/hyperledger/orderer/genesis.block
    volumes:
      - ./channel-artifacts/genesis.block:/var/hyperledger/orderer/genesis.block
      - ./crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/msp:/var/hyperledger/orderer/msp
      - ./crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/tls:/var/hyperledger/orderer/tls
    ports:
      - 7050:7050
    networks:
      - fabric
  ca.org1.example.com:
    container_name: ca.org1.example.com
    image: hyperledger/fabric-ca:1.5
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-org1
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=7054
    volumes:
      - ./crypto-config/peerOrganizations/org1.example.com/ca:/etc/hyperledger/fabric-ca-server
    ports:
      - 7054:7054
    networks:
      - fabric
  peer0.org1.example.com:
    container_name: peer0.org1.example.com
    image: hyperledger/fabric-peer:2.4
    environment:
      - CORE_PEER_ID=peer0.org1.example.com
      - CORE_PEER_ADDRESS=peer0.org1.example.com:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_LOCALMSPDIR=/var/hyperledger/peer/msp
      - CORE_PEER_MSPCONFIGPATH=/var/hyperledger/peer/msp
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org1.example.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org1.example.com:7051
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=host
      - FABRIC_LOGGING_SPEC=INFO
    volumes:
      - ./crypto-config/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/msp:/var/hyperledger/peer/msp
      - ./crypto-config/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls:/var/hyperledger/peer/tls
      - /var/run/docker.sock:/host/var/run/docker.sock
    ports:
      - 7051:7051
    networks:
      - fabric
  ca.org2.example.com:
    container_name: ca.org2.example.com
    image: hyperledger/fabric-ca:1.5
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-org2
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=8054
    volumes:
      - ./crypto-config/peerOrganizations/org2.example.com/ca:/etc/hyperledger/fabric-ca-server
    ports:
      - 8054:8054
    networks:
      - fabric
  peer0.org2.example.com:
    container_name: peer0.org2.example.com
    image: hyperledger/fabric-peer:2.4
    environment:
      - CORE_PEER_ID=peer0.org2.example.com
      - CORE_PEER_ADDRESS=peer0.org2.example.com:8051
      - CORE_PEER_LOCALMSPID=Org2MSP
      - CORE_PEER_LOCALMSPDIR=/var/hyperledger/peer/msp
      - CORE_PEER_MSPCONFIGPATH=/var/hyperledger/peer/msp
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org2.example.com:8051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org2.example.com:8051
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=host
      - FABRIC_LOGGING_SPEC=INFO
    volumes:
      - ./crypto-config/peerOrganizations/org2.example.com/peers/peer0.org2.example.com/msp:/var/hyperledger/peer/msp
      - ./crypto-config/peerOrganizations/org2.example.com/peers/peer0.org2.example.com/tls:/var/hyperledger/peer/tls
      - /var/run/docker.sock:/host/var/run/docker.sock
    ports:
      - 8051:8051
    networks:
      - fabric
  ca.org3.example.com:
    container_name: ca.org3.example.com
    image: hyperledger/fabric-ca:1.5
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-org3
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=9054
    volumes:
      - ./crypto-config/peerOrganizations/org3.example.com/ca:/etc/hyperledger/fabric-ca-server
    ports:
      - 9054:9054
    networks:
      - fabric
  peer0.org3.example.com:
    container_name: peer0.org3.example.com
    image: hyperledger/fabric-peer:2.4
    environment:
      - CORE_PEER_ID=peer0.org3.example.com
      - CORE_PEER_ADDRESS=peer0.org3.example.com:9051
      - CORE_PEER_LOCALMSPID=Org3MSP
      - CORE_PEER_LOCALMSPDIR=/var/hyperledger/peer/msp
      - CORE_PEER_MSPCONFIGPATH=/var/hyperledger/peer/msp
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org3.example.com:9051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org3.example.com:9051
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=host
      - FABRIC_LOGGING_SPEC=INFO
    volumes:
      - ./crypto-config/peerOrganizations/org3.example.com/peers/peer0.org3.example.com/msp:/var/hyperledger/peer/msp
      - ./crypto-config/peerOrganizations/org3.example.com/peers/peer0.org3.example.com/tls:/var/hyperledger/peer/tls
      - /var/run/docker.sock:/host/var/run/docker.sock
    ports:
      - 9051:9051
    networks:
      - fabric
  ca.org4.example.com:
    container_name: ca.org4.example.com
    image: hyperledger/fabric-ca:1.5
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-org4
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=10054
    volumes:
      - ./crypto-config/peerOrganizations/org4.example.com/ca:/etc/hyperledger/fabric-ca-server
    ports:
      - 10054:10054
    networks:
      - fabric
  peer0.org4.example.com:
    container_name: peer0.org4.example.com
    image: hyperledger/fabric-peer:2.4
    environment:
      - CORE_PEER_ID=peer0.org4.example.com
      - CORE_PEER_ADDRESS=peer0.org4.example.com:10051
      - CORE_PEER_LOCALMSPID=Org4MSP
      - CORE_PEER_LOCALMSPDIR=/var/hyperledger/peer/msp
      - CORE_PEER_MSPCONFIGPATH=/var/hyperledger/peer/msp
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org4.example.com:10051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org4.example.com:10051
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=host
      - FABRIC_LOGGING_SPEC=INFO
    volumes:
      - ./crypto-config/peerOrganizations/org4.example.com/peers/peer0.org4.example.com/msp:/var/hyperledger/peer/msp
      - ./crypto-config/peerOrganizations/org4.example.com/peers/peer0.org4.example.com/tls:/var/hyperledger/peer/tls
      - /var/run/docker.sock:/host/var/run/docker.sock
    ports:
      - 10051:10051
    networks:
      - fabric
  ca.org5.example.com:
    container_name: ca.org5.example.com
    image: hyperledger/fabric-ca:1.5
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-org5
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=11054
    volumes:
      - ./crypto-config/peerOrganizations/org5.example.com/ca:/etc/hyperledger/fabric-ca-server
    ports:
      - 11054:11054
    networks:
      - fabric
  peer0.org5.example.com:
    container_name: peer0.org5.example.com
    image: hyperledger/fabric-peer:2.4
    environment:
      - CORE_PEER_ID=peer0.org5.example.com
      - CORE_PEER_ADDRESS=peer0.org5.example.com:11051
      - CORE_PEER_LOCALMSPID=Org5MSP
      - CORE_PEER_LOCALMSPDIR=/var/hyperledger/peer/msp
      - CORE_PEER_MSPCONFIGPATH=/var/hyperledger/peer/msp
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org5.example.com:11051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org5.example.com:11051
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=host
      - FABRIC_LOGGING_SPEC=INFO
    volumes:
      - ./crypto-config/peerOrganizations/org5.example.com/peers/peer0.org5.example.com/msp:/var/hyperledger/peer/msp
      - ./crypto-config/peerOrganizations/org5.example.com/peers/peer0.org5.example.com/tls:/var/hyperledger/peer/tls
      - /var/run/docker.sock:/host/var/run/docker.sock
    ports:
      - 11051:11051
    networks:
      - fabric
  ca.org6.example.com:
    container_name: ca.org6.example.com
    image: hyperledger/fabric-ca:1.5
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-org6
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=12054
    volumes:
      - ./crypto-config/peerOrganizations/org6.example.com/ca:/etc/hyperledger/fabric-ca-server
    ports:
      - 12054:12054
    networks:
      - fabric
  peer0.org6.example.com:
    container_name: peer0.org6.example.com
    image: hyperledger/fabric-peer:2.4
    environment:
      - CORE_PEER_ID=peer0.org6.example.com
      - CORE_PEER_ADDRESS=peer0.org6.example.com:12051
      - CORE_PEER_LOCALMSPID=Org6MSP
      - CORE_PEER_LOCALMSPDIR=/var/hyperledger/peer/msp
      - CORE_PEER_MSPCONFIGPATH=/var/hyperledger/peer/msp
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org6.example.com:12051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org6.example.com:12051
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=host
      - FABRIC_LOGGING_SPEC=INFO
    volumes:
      - ./crypto-config/peerOrganizations/org6.example.com/peers/peer0.org6.example.com/msp:/var/hyperledger/peer/msp
      - ./crypto-config/peerOrganizations/org6.example.com/peers/peer0.org6.example.com/tls:/var/hyperledger/peer/tls
      - /var/run/docker.sock:/host/var/run/docker.sock
    ports:
      - 12051:12051
    networks:
      - fabric
  ca.org7.example.com:
    container_name: ca.org7.example.com
    image: hyperledger/fabric-ca:1.5
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-org7
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=13054
    volumes:
      - ./crypto-config/peerOrganizations/org7.example.com/ca:/etc/hyperledger/fabric-ca-server
    ports:
      - 13054:13054
    networks:
      - fabric
  peer0.org7.example.com:
    container_name: peer0.org7.example.com
    image: hyperledger/fabric-peer:2.4
    environment:
      - CORE_PEER_ID=peer0.org7.example.com
      - CORE_PEER_ADDRESS=peer0.org7.example.com:13051
      - CORE_PEER_LOCALMSPID=Org7MSP
      - CORE_PEER_LOCALMSPDIR=/var/hyperledger/peer/msp
      - CORE_PEER_MSPCONFIGPATH=/var/hyperledger/peer/msp
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org7.example.com:13051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org7.example.com:13051
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=host
      - FABRIC_LOGGING_SPEC=INFO
    volumes:
      - ./crypto-config/peerOrganizations/org7.example.com/peers/peer0.org7.example.com/msp:/var/hyperledger/peer/msp
      - ./crypto-config/peerOrganizations/org7.example.com/peers/peer0.org7.example.com/tls:/var/hyperledger/peer/tls
      - /var/run/docker.sock:/host/var/run/docker.sock
    ports:
      - 13051:13051
    networks:
      - fabric
  ca.org8.example.com:
    container_name: ca.org8.example.com
    image: hyperledger/fabric-ca:1.5
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-org8
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=14054
    volumes:
      - ./crypto-config/peerOrganizations/org8.example.com/ca:/etc/hyperledger/fabric-ca-server
    ports:
      - 14054:14054
    networks:
      - fabric
  peer0.org8.example.com:
    container_name: peer0.org8.example.com
    image: hyperledger/fabric-peer:2.4
    environment:
      - CORE_PEER_ID=peer0.org8.example.com
      - CORE_PEER_ADDRESS=peer0.org8.example.com:14051
      - CORE_PEER_LOCALMSPID=Org8MSP
      - CORE_PEER_LOCALMSPDIR=/var/hyperledger/peer/msp
      - CORE_PEER_MSPCONFIGPATH=/var/hyperledger/peer/msp
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org8.example.com:14051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org8.example.com:14051
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=host
      - FABRIC_LOGGING_SPEC=INFO
    volumes:
      - ./crypto-config/peerOrganizations/org8.example.com/peers/peer0.org8.example.com/msp:/var/hyperledger/peer/msp
      - ./crypto-config/peerOrganizations/org8.example.com/peers/peer0.org8.example.com/tls:/var/hyperledger/peer/tls
      - /var/run/docker.sock:/host/var/run/docker.sock
    ports:
      - 14051:14051
    networks:
      - fabric
  ca.org9.example.com:
    container_name: ca.org9.example.com
    image: hyperledger/fabric-ca:1.5
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-org9
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=15054
    volumes:
      - ./crypto-config/peerOrganizations/org9.example.com/ca:/etc/hyperledger/fabric-ca-server
    ports:
      - 15054:15054
    networks:
      - fabric
  peer0.org9.example.com:
    container_name: peer0.org9.example.com
    image: hyperledger/fabric-peer:2.4
    environment:
      - CORE_PEER_ID=peer0.org9.example.com
      - CORE_PEER_ADDRESS=peer0.org9.example.com:15051
      - CORE_PEER_LOCALMSPID=Org9MSP
      - CORE_PEER_LOCALMSPDIR=/var/hyperledger/peer/msp
      - CORE_PEER_MSPCONFIGPATH=/var/hyperledger/peer/msp
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org9.example.com:15051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org9.example.com:15051
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=host
      - FABRIC_LOGGING_SPEC=INFO
    volumes:
      - ./crypto-config/peerOrganizations/org9.example.com/peers/peer0.org9.example.com/msp:/var/hyperledger/peer/msp
      - ./crypto-config/peerOrganizations/org9.example.com/peers/peer0.org9.example.com/tls:/var/hyperledger/peer/tls
      - /var/run/docker.sock:/host/var/run/docker.sock
    ports:
      - 15051:15051
    networks:
      - fabric
  ca.org10.example.com:
    container_name: ca.org10.example.com
    image: hyperledger/fabric-ca:1.5
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-org10
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=16054
    volumes:
      - ./crypto-config/peerOrganizations/org10.example.com/ca:/etc/hyperledger/fabric-ca-server
    ports:
      - 16054:16054
    networks:
      - fabric
  peer0.org10.example.com:
    container_name: peer0.org10.example.com
    image: hyperledger/fabric-peer:2.4
    environment:
      - CORE_PEER_ID=peer0.org10.example.com
      - CORE_PEER_ADDRESS=peer0.org10.example.com:16051
      - CORE_PEER_LOCALMSPID=Org10MSP
      - CORE_PEER_LOCALMSPDIR=/var/hyperledger/peer/msp
      - CORE_PEER_MSPCONFIGPATH=/var/hyperledger/peer/msp
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org10.example.com:16051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org10.example.com:16051
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=host
      - FABRIC_LOGGING_SPEC=INFO
    volumes:
      - ./crypto-config/peerOrganizations/org10.example.com/peers/peer0.org10.example.com/msp:/var/hyperledger/peer/msp
      - ./crypto-config/peerOrganizations/org10.example.com/peers/peer0.org10.example.com/tls:/var/hyperledger/peer/tls
      - /var/run/docker.sock:/host/var/run/docker.sock
    ports:
      - 16051:16051
    networks:
      - fabric
