---
number: 1000
rate: 100
chaincodeID: GeoAssign
channel: generalchannelapp
contractFunction: AssignEntity
contractArguments:
  - entity${i}
  - ${Math.random() * 500}
  - ${Math.random() * 500}
orderer: grpc://orderer1.example.com:7050
tls:
  enabled: true
  caFile: crypto/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/ca.crt
peers:
  - grpc://peer0.org1.example.com:7051
  - grpc://peer0.org2.example.com:8051
  - grpc://peer0.org3.example.com:9051
  - grpc://peer0.org4.example.com:10051
  - grpc://peer0.org5.example.com:11051
  - grpc://peer0.org6.example.com:12051
  - grpc://peer0.org7.example.com:13051
  - grpc://peer0.org8.example.com:14051
  - grpc://peer0.org9.example.com:15051
  - grpc://peer0.org10.example.com:16051
msp:
  id: Org1MSP
  path: crypto/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp
